add terminate flag to kill
heroku/heroku-pg pull request #208
Opened 2018-05-26 16:43 UTC by mehtaphysical

Right now with `heroku sudo` the force flag is not sent because sudo also uses force. This PR adds a terminate flag as a workaround.

2018-05-26 16:44 UTC, mehtaphysical commented
![](https://github.trello.services/images/mini-trello-icon.png) [heroku sudo command doesn't pass flags](https://trello.com/c/6TUssHmx/839-heroku-sudo-command-doesnt-pass-flags)

2018-05-29 16:47 UTC, msakrejda requested changes
This seems to be more of heroku sudo problem than a heroku-pg problem. I would really like to avoid changing customer-facing commands to work around the limitations of an internal plugin.

If there is no other way to work around this, can we hide the second flag so customers don't see two different flags for the same thing?

2018-05-29 18:26 UTC, mehtaphysical commented
@uhoh-itsmaciek for sure. Which way would you prefer to do it? Also, @tcrayford

2018-05-29 19:03 UTC, msakrejda commented
Well, it looks like a bunch of other commands have `--force` flags:

```
msakrejda@localhost:~$ for command in $(h commands); do h help $command | sed "s/^/$command: /"; done | grep force
addons:destroy:   -f, --force            allow destruction even if connected to other apps
addons:remove:   -f, --force            allow destruction even if connected to other apps
builds:push:   -f, --force          force push to overwrite remote branch
logs:   --force-colors       force use of colors (even on non-tty output)
pg:credentials:rotate:   --force                forces rotating the targeted credentials
pg:kill:   -f, --force
pg:maintenance:run:   -f, --force
rake:   --no-tty             force the command to not run in a tty
redis:maintenance:   -f, --force          start maintenance without entering application
run:   --no-tty             force the command to not run in a tty
sudo:   -f, --force
```

So other than the bogus matches of `logs`, `run`, `rake`, and `sudo`, you'd need to change all these other commands to work around the issue (and that's just for the plugins that I have installed). Can we change `sudo` instead? Any generic flags on that command are going to have a bunch of awkward conflicts.

Or does oclif support `--`? We could do something like `heroku sudo --force -- pg:kill --force` then...

2018-05-29 19:03 UTC, uhoh-itsmaciek commented
Any thoughts on the comment above @jdxcode?

2018-05-29 19:07 UTC, jdx commented
I agree with @uhoh-itsmaciek and this is why we have the `--` argument. Just use `heroku sudo -u someuser -- pg:kill -f`.

If you read the help for `heroku help sudo` it always uses the `--` for this reason.

2018-05-29 19:14 UTC, uhoh-itsmaciek commented
Oh I had no idea this works already. Neat. In that case, I think we can consider this moot? I'm closing; please reopen if you hit issues with `--`.

2018-05-29 19:14 UTC, closed without merging