added pg:backups:download
heroku/heroku-pg pull request #27
Opened 2016-10-08 07:30 UTC by dickeyxxx

2016-11-02 00:11 UTC, msakrejda requested changes

2016-11-02 00:11 UTC, uhoh-itsmaciek commented on test/commands/backups/cancel.js
> +    it('shows URL', () => {
That doesn't seem like the right test description.

2016-11-02 00:11 UTC, uhoh-itsmaciek commented on test/commands/backups/cancel.js
> +    it('shows URL', () => {
Ditto.

2016-11-16 18:37 UTC, dickeyxxx commented on test/commands/backups/cancel.js
> +    it('shows URL', () => {
fixed

2016-11-16 18:53 UTC, msakrejda approved these changes

2016-11-17 19:53 UTC, merged