added pg:backups:schedule
heroku/heroku-pg pull request #31
Opened 2016-10-09 01:21 UTC by dickeyxxx

needs a test

2016-11-01 23:40 UTC, msakrejda requested changes

2016-11-01 23:40 UTC, uhoh-itsmaciek commented on commands/backups/schedule.js
> +  let schedule = parse(flags.at)
Might as well parse this before fetching the DB above--there's no point in continuing if the time is invalid.

2016-11-16 18:42 UTC, jdx commented on commands/backups/schedule.js
> +  let schedule = parse(flags.at)
fixed

2016-11-16 19:12 UTC, msakrejda approved these changes

2016-11-17 19:27 UTC, merged