added pg:links
heroku/heroku-pg pull request #41
Opened 2016-10-11 04:34 UTC by dickeyxxx

2016-11-01 20:38 UTC, msakrejda requested changes

2016-11-01 20:38 UTC, uhoh-itsmaciek commented on commands/links/destroy.js
> +  heroku pg:links:create HEROKU_POSTGRESQL_CERULEAN redis_symmetrical_100`,
this should be `pg:links:destroy`, no? Also the link target name is not a standard format we use--should this be something like `redis-symmetrical-100` instead?

2016-11-01 20:38 UTC, uhoh-itsmaciek commented on test/commands/links/create.js
> +    .then(() => expect(cli.stderr, 'to equal', 'Adding link from postgres-1 to postgres-1... foobar\n'))
This reads kinda weird... should we  change this to `... done; added foobar` or `... added foobar` or something? /cc @neovintage

2016-11-11 20:34 UTC, dickeyxxx commented on commands/links/destroy.js
> +  heroku pg:links:create HEROKU_POSTGRESQL_CERULEAN redis_symmetrical_100`,
yes to both, fixed

2016-11-11 20:38 UTC, dickeyxxx commented on test/commands/links/create.js
> +    .then(() => expect(cli.stderr, 'to equal', 'Adding link from postgres-1 to postgres-1... foobar\n'))
👍  to making it more clear, updated

2016-11-14 18:39 UTC, msakrejda approved these changes

2016-11-17 19:13 UTC, merged