[WIP] Support bastions
heroku/heroku-pg pull request #45
Opened 2016-11-16 14:08 UTC by idan

/cc @heroku/dod-ux

Right now none of the heroku/heroku-pg-extras commands will work for private dbs because they don't know how to set up a tunnel through the bastion.

2016-11-16 14:09 UTC, idan commented
I have to run, @camilleldn taking over

2016-11-16 14:42 UTC, camilleldn commented
I have split https://github.com/heroku/heroku-pg/pull/46 (fixing the config var lookup bug for private databases) out as a separate pull request. This PR should focus on implementing SSH tunneling for databases behind bastions.

2016-11-16 16:10 UTC, camilleldn commented
https://github.com/heroku/heroku-redis-jsplugin/blob/master/lib/commands/redis/cli.js#L110 for future reference

2016-11-21 21:59 UTC, jdx requested changes

2016-11-21 21:59 UTC, dickeyxxx commented on lib/psql.js
> +    PGSSLMODE: db.host === 'localhost' ? 'prefer' : 'require',
shouldn't this be `hostname`?

2016-11-21 21:59 UTC, dickeyxxx commented on lib/psql.js
> +  const tunnelPromise = buildTunnelPromise(db, configs.dbTunnelConfig, timeout)
This section could be more direct:

```js
yield buildTunnelPromise(db, configs.dbTunnelConfig, timeout)
return yield buildPsqlPromise(query, configs.dbEnv, timeout)
```

Also the names of these functions should probably be something more like `tunnel()` or `createTunnel()` and `execPSQL()` or `psql()`. The fact it's generating a promise isn't as important as what the function does.

2016-11-21 21:59 UTC, dickeyxxx commented on lib/psql.js
> +    psql.stdout.on('data', (data) => {
I worry this might not work if the output is large. Maybe we could test it with the `pg:mandelbrot` repeated a few times?

2016-11-21 21:59 UTC, dickeyxxx commented on lib/psql.js
> +      tunnel(dbTunnelConfig, (err, tnl) => {
it would be nice if we had test coverage over this section

2016-11-21 22:09 UTC, dickeyxxx commented on lib/psql.js
> +  return new Promise((resolve, reject) => {
this is creating a promise that's never resolved

2016-11-21 22:16 UTC, msakrejda requested changes
Mostly looks good, although I think we need to tweak stdout handling to make sure we get it all (if, e.g., there are multiple "chunks"). Other than that just some style comments.

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +    PGSSLMODE: db.host === 'localhost' ? 'prefer' : 'require',
Shouldn't this be `hostname`? `host` includes the port if one is set explicitly, which should be moot for the purpose of this conditional.

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +          process.exit(1)
The `heroku-cli` convention is to throw an error rather than `cli.error` and exit.

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +    cli.error(error)
I think you can drop this `catch`, no? You want to propagate the error anyway to ensure the program terminates (since establishing the tunnel is necessary for this to work).

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +      resolve(stripEOF(data))
Can `stdout` produce a 'data' event multiple times? What happens in that case? Maybe we want to accumulate and then concatenate the produced data and resolve the promise on process exit?

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +      process.exit(1)
I don't think that anything on stderr is automatically an error...

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +      handleError(err)
This uses the same handler that tells you you don't seem to have `psql` installed which isn't really true. Maybe just `reject`?

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +    setTimeout(() => reject('psql call timed out'), timeout)
Nice.

2016-11-21 22:16 UTC, msakrejda commented on lib/psql.js
> +          process.exit(1)
Although I guess you're in a promise here so maybe `reject` the promise instead? I suppose if you want to definitely exit immediately you can do this, but it feels weird to have that buried in here.

2016-11-21 22:16 UTC, uhoh-itsmaciek commented on lib/psql.js
> +    cli.error(error)
Same here, why not just `reject`?

2016-11-21 22:16 UTC, uhoh-itsmaciek commented on lib/psql.js
> +      handleError(err)
Same as above, I think `reject`-ing would be clearer here, no?

2016-11-21 22:16 UTC, uhoh-itsmaciek commented on lib/psql.js
> +  const command = tunnelPromise.then((tnl) => {
Also the explicit `promise` naming seems a little idiosyncratic: most JS I've seen handles that implicitly (e.g., maybe something like

```javascript
const tunnel = buildTunnel(...)
const command = tunnel.then((tnl) => runPsql(query, ...)
```

or something). I think the specific naming and formatting is not that important, but referencing promises explicitly feels clunky.

2016-11-21 22:17 UTC, uhoh-itsmaciek commented
@dickeyxxx may also want to take a look...

2016-11-21 22:23 UTC, uhoh-itsmaciek commented
Ha @dickeyxxx has already had a look. Thanks!

2016-11-21 23:49 UTC, camillebaldock commented on lib/psql.js
> +    psql.stdout.on('data', (data) => {
correct, it just hangs on massive query results. i'm fixing

2016-11-22 15:38 UTC, camilleldn commented on lib/psql.js
> +      tunnel(dbTunnelConfig, (err, tnl) => {
done :)

2016-11-22 15:58 UTC, camilleldn commented
@uhoh-itsmaciek @dickeyxxx addressed a bunch of your comments, thanks again for your review ❤️ , I would appreciate a final look now that the code has changed :)

2016-11-22 17:05 UTC, jdx requested changes
looks pretty good, a couple more things I'd like to see fixed though

2016-11-22 17:05 UTC, jdx commented on lib/psql.js
> +    psql.on('error', (err) => {
seems like this function could be shared with line 71

2016-11-22 17:05 UTC, dickeyxxx commented on lib/psql.js
> +    process.exit(1)
ideally it should fail with the same status code that `psql` failed with, probably the same in non-interactive

2016-11-22 17:05 UTC, dickeyxxx commented on lib/psql.js
> +    psql.stderr.on('data', (data) => {
we should just propagate stderr out to the terminal like we did before. Just because there is something on stderr doesn't mean it's an error either.

2016-11-22 17:05 UTC, dickeyxxx commented on lib/psql.js
> +  }).catch((error) => {
no need to catch this, just let the error propagate

2016-11-22 17:05 UTC, dickeyxxx commented on lib/psql.js
> +  const tunnelPromise = sshTunnel(db, configs.dbTunnelConfig, timeout)
I would like to see these lines use generators instead:

```js
yield sshTunnel(db, configs.dbTunnelConfig, timeout)
yield execPsql(query, configs.dbEnv, timeout)
```

2016-11-22 17:22 UTC, msakrejda commented on lib/psql.js
> +    psql.stderr.on('data', (data) => {
Yeah, that makes sense. So `stdio: [ 'ignore', 'pipe', 'inherit' ]` in `spawn` above, right?

2016-11-22 17:23 UTC, uhoh-itsmaciek commented on lib/psql.js
> +        reject(`The local psql command could not be located. For help installing psql, see https://devcenter.heroku.com/articles/heroku-postgresql#local-setup`)
Nice

2016-11-22 17:24 UTC, uhoh-itsmaciek commented on lib/psql.js
> +    psql.on('error', (err) => {
Yeah, if you just bring it up to top level, you can share it pretty easily.

2016-11-22 17:27 UTC, uhoh-itsmaciek commented on lib/psql.js
> +    resolve()
Don't you want to wait for the program to exit (`.on('close')`) to resolve this?

2016-11-22 18:23 UTC, dickeyxxx commented on lib/psql.js
> +    psql.stderr.on('data', (data) => {
we could probably pipe in stdin as well, though I'm not sure if psql would ever use it

2016-11-22 18:46 UTC, uhoh-itsmaciek commented on lib/psql.js
> +    psql.stderr.on('data', (data) => {
I think it ignores it if you pass `-c`:

```
maciek@mothra:~$ <<<'select 2' psql -qc 'select 1'
 ?column? 
----------
        1
(1 row)
```

2016-11-22 21:12 UTC, uhoh-itsmaciek commented on lib/psql.js
> +      Promise.reject(err)
Shouldn't this also be `reject(err)`?

2016-11-22 21:14 UTC, uhoh-itsmaciek commented on lib/psql.js
> +    setTimeout(() => reject('Establishing a secure tunnel timed out'), timeout)
Oh ugh I just realized that if you do this I think you need to cancel the timeout (with the token from the return value of `setTimeout`) when the tunnel does resolve successfully (or isn't needed). I think it's also fine to skip the timeout instead.

2016-11-22 22:19 UTC, msakrejda commented on lib/psql.js
> +    setTimeout(() => reject('psql call timed out'), timeout)
Same as above re: timeout.

2016-11-22 22:30 UTC, uhoh-itsmaciek commented
Ok, some tiny comments left (I'd drop the `setTimeouts` for now if you don't feel like adding the cancellation--I don't think that's that'd big a deal).

2016-11-23 00:58 UTC, uhoh-itsmaciek commented
+1 :tada:

2016-11-23 00:58 UTC, msakrejda approved these changes

2016-11-23 11:11 UTC, camilleldn commented
@dickeyxxx any last feedback? :)

2016-11-28 18:14 UTC, jdx requested changes

2016-11-28 18:14 UTC, dickeyxxx commented on test/lib/psql.js
> +const Code = require('code')
can we use `unexpected` instead since it's already used by this project?

2016-11-29 14:36 UTC, camilleldn commented on test/lib/psql.js
> +const Code = require('code')
fixed :)

2016-11-29 15:09 UTC, dickeyxxx commented on package.json
> +    "code": "^4.0.0",
We don't need this now

2016-11-29 15:50 UTC, jdx approved these changes

2016-11-29 17:26 UTC, merged