Fix ambiguity errors & implicit attachments
heroku/heroku-pg pull request #56
Opened 2016-11-22 17:40 UTC by ransombriggs

@dickeyxxx could you review?

2016-11-22 18:22 UTC, jdx requested changes

2016-11-22 18:22 UTC, dickeyxxx commented on lib/config.js
> +module.exports = memoizePromise(config, (_heroku, app) => app)
nice

2016-11-22 18:22 UTC, dickeyxxx commented on lib/fetcher.js
> +    function * matchesHelper (app, db) {
while this works, you should wrap it in `co.wrap()` so it's a regular promise

2016-11-22 18:22 UTC, dickeyxxx commented on lib/fetcher.js
> +      .then(attached => ({matches: [attached], err: null}))
shouldn't be necessary to pass the null err here

2016-11-22 18:22 UTC, dickeyxxx commented on lib/fetcher.js
> +    let {matches, err} = yield matchesHelper(app, db)
I love this pattern. Multiple return objects is super useful.

2016-11-22 18:22 UTC, dickeyxxx commented on lib/memoize_promise.js
> +  memoized.cache = new memoize.Cache()
do we really need to use `lodash.memoize`? I think if you replaced this line with `memoized.cache = new WeakMap()` it would be equivalent.

2016-11-22 19:41 UTC, ransombriggs commented
@dickeyxxx made changes in response to feedback in https://github.com/heroku/heroku-pg/pull/56/commits/6dd7be80dc16b2f24a1630f44ba6e15999b57766

2016-11-23 02:54 UTC, ransombriggs commented
@dickeyxxx I pushed up two more commits to fix bugs I found, I think this is ready for @uhoh-itsmaciek after your review.

2016-11-28 18:15 UTC, jdx approved these changes

2016-11-28 19:30 UTC, merged